"""add address column

Revision ID: 05d05f698d17
Revises:
Create Date: 2026-02-13 18:26:33.751011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "05d05f698d17"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "branch_metrics",
        "date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Date(),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        "uq_branch_metrics_branch_date", "branch_metrics", ["branch_id", "date"]
    )
    op.create_foreign_key(None, "branch_metrics", "stores", ["branch_id"], ["id"])
    op.add_column(
        "customers", sa.Column("address", sa.String(length=255), nullable=True)
    )
    op.add_column("customers", sa.Column("birth_date", sa.Date(), nullable=True))
    op.add_column("customers", sa.Column("age", sa.Integer(), nullable=True))
    op.add_column("customers", sa.Column("description", sa.Text(), nullable=True))
    op.create_foreign_key(None, "customers", "stores", ["preferred_branch"], ["id"])
    op.alter_column(
        "face_embeddings", "embedding", existing_type=Vector(dim=512), nullable=False
    )
    op.drop_index(
        "face_embeddings_embedding_hnsw",
        table_name="face_embeddings",
        postgresql_using="hnsw",
    )
    op.create_foreign_key(
        None,
        "face_embeddings",
        "customers",
        ["customer_id"],
        ["customer_id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "inventory_optimizations",
        "product_id",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="product_id::integer",
    )
    op.create_unique_constraint(
        "uq_inventory_opt_branch_product_action",
        "inventory_optimizations",
        ["branch_id", "product_id", "action"],
    )
    op.create_foreign_key(
        None, "inventory_optimizations", "products", ["product_id"], ["id"]
    )
    op.add_column("products", sa.Column("product_code", sa.String(), nullable=True))
    op.add_column("products", sa.Column("discount_price", sa.Float(), nullable=True))
    op.add_column("products", sa.Column("discount_percent", sa.Float(), nullable=True))
    op.add_column("products", sa.Column("description", sa.Text(), nullable=True))
    op.drop_index("ix_products_product_id", table_name="products")
    op.create_index(
        op.f("ix_products_product_code"), "products", ["product_code"], unique=True
    )
    op.drop_column("products", "product_id")
    op.add_column(
        "recommendations", sa.Column("device_id", sa.String(length=50), nullable=False)
    )
    op.create_index(
        op.f("ix_recommendations_device_id"),
        "recommendations",
        ["device_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "recommendations", "customers", ["customer_id"], ["customer_id"]
    )
    op.create_foreign_key(
        None, "recommendations", "edge_devices", ["device_id"], ["id"]
    )
    op.create_foreign_key(None, "recommendations", "stores", ["branch_id"], ["id"])
    op.alter_column(
        "transaction_items",
        "product_id",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Integer(),
        nullable=False,
    )
    op.create_index(
        op.f("ix_transaction_items_transaction_id"),
        "transaction_items",
        ["transaction_id"],
        unique=False,
    )
    op.drop_constraint(
        "transaction_items_product_id_fkey", "transaction_items", type_="foreignkey"
    )
    op.create_foreign_key(None, "transaction_items", "products", ["product_id"], ["id"])
    op.add_column(
        "transactions", sa.Column("device_id", sa.String(length=50), nullable=False)
    )
    op.create_index(
        op.f("ix_transactions_device_id"), "transactions", ["device_id"], unique=False
    )
    op.create_foreign_key(None, "transactions", "edge_devices", ["device_id"], ["id"])
    op.create_foreign_key(None, "transactions", "stores", ["branch_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.drop_index(op.f("ix_transactions_device_id"), table_name="transactions")
    op.drop_column("transactions", "device_id")
    op.drop_constraint(None, "transaction_items", type_="foreignkey")
    op.create_foreign_key(
        "transaction_items_product_id_fkey",
        "transaction_items",
        "products",
        ["product_id"],
        ["product_id"],
    )
    op.drop_index(
        op.f("ix_transaction_items_transaction_id"), table_name="transaction_items"
    )
    op.alter_column(
        "transaction_items",
        "product_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.drop_constraint(None, "recommendations", type_="foreignkey")
    op.drop_constraint(None, "recommendations", type_="foreignkey")
    op.drop_constraint(None, "recommendations", type_="foreignkey")
    op.drop_index(op.f("ix_recommendations_device_id"), table_name="recommendations")
    op.drop_column("recommendations", "device_id")
    op.add_column(
        "products",
        sa.Column("product_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_products_product_code"), table_name="products")
    op.create_index("ix_products_product_id", "products", ["product_id"], unique=True)
    op.drop_column("products", "description")
    op.drop_column("products", "discount_percent")
    op.drop_column("products", "discount_price")
    op.drop_column("products", "product_code")
    op.drop_constraint(None, "inventory_optimizations", type_="foreignkey")
    op.drop_constraint(
        "uq_inventory_opt_branch_product_action",
        "inventory_optimizations",
        type_="unique",
    )
    op.alter_column(
        "inventory_optimizations",
        "product_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_constraint(None, "face_embeddings", type_="foreignkey")
    op.create_index(
        "face_embeddings_embedding_hnsw",
        "face_embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
    )
    op.alter_column(
        "face_embeddings",
        "embedding",
        existing_type=Vector(dim=512),
        nullable=True,
    )
    op.drop_constraint(None, "customers", type_="foreignkey")
    op.drop_column("customers", "description")
    op.drop_column("customers", "age")
    op.drop_column("customers", "birth_date")
    op.drop_column("customers", "address")
    op.drop_constraint(None, "branch_metrics", type_="foreignkey")
    op.drop_constraint(
        "uq_branch_metrics_branch_date", "branch_metrics", type_="unique"
    )
    op.alter_column(
        "branch_metrics",
        "date",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
