"""add branch_inventory

Revision ID: ba1844d87eb9
Revises: 
Create Date: 2025-12-13 01:03:13.539033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1844d87eb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'product_id', name='uq_branch_inventory_branch_product')
    )
    op.create_index(op.f('ix_branch_inventory_branch_id'), 'branch_inventory', ['branch_id'], unique=False)
    op.create_index('ix_branch_inventory_branch_stock', 'branch_inventory', ['branch_id', 'stock'], unique=False)
    op.create_index(op.f('ix_branch_inventory_id'), 'branch_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_branch_inventory_product_id'), 'branch_inventory', ['product_id'], unique=False)
    op.drop_constraint('promotion_branches_promotion_id_fkey', 'promotion_branches', type_='foreignkey')
    op.create_foreign_key(None, 'promotion_branches', 'stores', ['branch_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'promotion_branches', 'promotions', ['promotion_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('promotion_products_product_id_fkey', 'promotion_products', type_='foreignkey')
    op.drop_constraint('promotion_products_promotion_id_fkey', 'promotion_products', type_='foreignkey')
    op.create_foreign_key(None, 'promotion_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'promotion_products', 'promotions', ['promotion_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promotion_products', type_='foreignkey')
    op.drop_constraint(None, 'promotion_products', type_='foreignkey')
    op.create_foreign_key('promotion_products_promotion_id_fkey', 'promotion_products', 'promotions', ['promotion_id'], ['id'])
    op.create_foreign_key('promotion_products_product_id_fkey', 'promotion_products', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'promotion_branches', type_='foreignkey')
    op.drop_constraint(None, 'promotion_branches', type_='foreignkey')
    op.create_foreign_key('promotion_branches_promotion_id_fkey', 'promotion_branches', 'promotions', ['promotion_id'], ['id'])
    op.drop_index(op.f('ix_branch_inventory_product_id'), table_name='branch_inventory')
    op.drop_index(op.f('ix_branch_inventory_id'), table_name='branch_inventory')
    op.drop_index('ix_branch_inventory_branch_stock', table_name='branch_inventory')
    op.drop_index(op.f('ix_branch_inventory_branch_id'), table_name='branch_inventory')
    op.drop_table('branch_inventory')
    # ### end Alembic commands ###
